version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "18080:8080"
      - "8443:8443"
    volumes:
      - ./keycloak/Default-export.json:/opt/keycloak/Default-export.json
      - ../resources/keystores/airavata.jks:/opt/jboss/keycloak/standalone/configuration/keystores/airavata.jks
      - ./keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    command:
      [
        "start-dev",
        "--import-realm"
      ]
    depends_on:
      - db

  db:
    image: mariadb:10.4.13
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=airavata
      - MYSQL_PASSWORD=123456
    volumes:
      - db_data:/var/lib/mysql
      - ./database_scripts/init:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=']

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_VHOST=develop
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - db

  zookeeper:
    image: zookeeper
    restart: always
    hostname: zk
    ports:
      - "12181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  sshd:
    image: dimuthuupe/sshd:1.0
    volumes:
      - /tmp:/tmp
    ports:
      - "22222:22"
    restart: always

volumes:
  db_data:
